Repository leeymin130/Caladium, pull requests merged in 2025-07, with the labels that each got.

#26 애니메이션 생성기 구현
  Caladium/Caladium/Resources/Assets.xcassets/sample1.imageset/Contents.json
  Caladium/Caladium/Resources/Assets.xcassets/sample1.imageset/sample1.png
  Caladium/Caladium/Resources/Assets.xcassets/sample2.imageset/Contents.json
  Caladium/Caladium/Resources/Assets.xcassets/sample2.imageset/sample2.png
  Caladium/Caladium/Resources/Assets.xcassets/sample3.imageset/Contents.json
  Caladium/Caladium/Resources/Assets.xcassets/sample3.imageset/sample3.png
  Caladium/Caladium/Resources/Assets.xcassets/sample4.imageset/Contents.json
  Caladium/Caladium/Resources/Assets.xcassets/sample4.imageset/sample4.png
  Caladium/Caladium/Resources/Assets.xcassets/sample5.imageset/Contents.json
  Caladium/Caladium/Resources/Assets.xcassets/sample5.imageset/sample5.png
  Caladium/Caladium/Resources/Assets.xcassets/sample6.imageset/Contents.json
  Caladium/Caladium/Resources/Assets.xcassets/sample6.imageset/sample6.png
  Caladium/Caladium/Services/GIFCreator.swift
  Caladium/Caladium/Services/VideoCreator.swift
  Caladium/Caladium/Views/Componenets/GIFPreviewView.swift
  Caladium/Caladium/Views/Componenets/MOVPreviewView.swift
  Caladium/Caladium/Views/Screen/GIFCreatorView.swift
Labels: feat

#36 전체 기능 연결
  Caladium/Caladium/App/CaladiumApp.swift
  Caladium/Caladium/App/ContentView.swift
  Caladium/Caladium/App/DependencyContainer.swift
  Caladium/Caladium/Navigation/AppCoordinator.swift
  Caladium/Caladium/Navigation/AppRoute.swift
  Caladium/Caladium/Services/CoreDataService.swift
  Caladium/Caladium/Services/VideoGenerationService.swift
  Caladium/Caladium/ViewModels/HomeViewModel.swift
  Caladium/Caladium/ViewModels/ProjectDetailViewModel.swift
  Caladium/Caladium/Views/Componenets/ActionButton.swift
  Caladium/Caladium/Views/Componenets/AsyncPhotoImage.swift
  Caladium/Caladium/Views/Componenets/CategoryChangePopup.swift
  Caladium/Caladium/Views/Componenets/FormatSelectPopupView.swift
  Caladium/Caladium/Views/Componenets/LoadingView.swift
  Caladium/Caladium/Views/Componenets/PhotoDeleteConfirmPopup.swift
  Caladium/Caladium/Views/Componenets/PhotoFrame.swift
  Caladium/Caladium/Views/Componenets/PhotoThumbnail.swift
  Caladium/Caladium/Views/Componenets/ProjectThumbnail.swift
  Caladium/Caladium/Views/Screen/AnimationResultView.swift
  Caladium/Caladium/Views/Screen/HomeView.swift
  Caladium/Caladium/Views/Screen/PhotoDetailView.swift
  Caladium/Caladium/Views/Screen/ProjectDetailView.swift
Labels: feat

#40 컴포넌트 잡아오기
  Caladium/Caladium/Views/Screen/HomeView.swift
  Caladium/Caladium/Views/Screen/ProjectDetailView.swift
Labels: enh

#41 Rive 의존성 추가 및 asset 추가
  Caladium/Caladium.xcodeproj/project.pbxproj
  Caladium/Caladium.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Caladium/Caladium/App/RiveViewSample.swift
  Caladium/Caladium/Resources/Rive-Assets/loading_jegeo.riv
  Caladium/Caladium/Resources/Rive-Assets/onboarding2.riv
  Caladium/Caladium/Resources/Rive-Assets/onboarding4.riv
  Caladium/Caladium/Resources/Rive-Assets/onborading1.riv
Labels: feat

#43 [feat] 커스텀 폰트 적용하기
  Caladium/Caladium.xcodeproj/project.pbxproj
  Caladium/Caladium/Info.plist
  Caladium/Caladium/Models/Category.swift
  Caladium/Caladium/Resources/Assets.xcassets/camera.imageset/Contents.json
  Caladium/Caladium/Resources/Assets.xcassets/camera.imageset/camera.svg
  Caladium/Caladium/Resources/Fonts/CustomFont.swift
  Caladium/Caladium/Resources/Fonts/Paperlogy-6SemiBold.ttf
  Caladium/Caladium/Resources/Fonts/SUIT-Bold.otf
  Caladium/Caladium/Resources/Fonts/SUIT-Regular.otf
  Caladium/Caladium/Resources/Fonts/SUIT-SemiBold.otf
  Caladium/Caladium/Views/Componenets/ActionButton.swift
  Caladium/Caladium/Views/Componenets/BottomToolbar.swift
  Caladium/Caladium/Views/Componenets/CategoryChangePopup.swift
  Caladium/Caladium/Views/Componenets/DeleteConfirmPopup.swift
  Caladium/Caladium/Views/Componenets/FormatSelectPopupView.swift
  Caladium/Caladium/Views/Componenets/PhotoDeleteConfirmPopup.swift
  Caladium/Caladium/Views/Componenets/PhotoFrame.swift
  Caladium/Caladium/Views/Componenets/PhotoThumbnail.swift
  Caladium/Caladium/Views/Componenets/ProjectAddButton.swift
  Caladium/Caladium/Views/Componenets/ProjectThumbnail.swift
  Caladium/Caladium/Views/Screen/AnimationResultView.swift
  Caladium/Caladium/Views/Screen/HomeView.swift
  Caladium/Caladium/Views/Screen/ProjectDetailView.swift
Labels: feat

#48 [Fix] UI design 검토 및 최종 수정
  Caladium/Caladium.xcodeproj/project.pbxproj
  Caladium/Caladium/Navigation/AppCoordinator.swift
  Caladium/Caladium/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Caladium/Caladium/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  Caladium/Caladium/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Caladium/Caladium/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Caladium/Caladium/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  Caladium/Caladium/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Caladium/Caladium/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  Caladium/Caladium/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Caladium/Caladium/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Caladium/Caladium/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Caladium/Caladium/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Caladium/Caladium/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Caladium/Caladium/Resources/Fonts/CustomFont.swift
  Caladium/Caladium/ViewModels/NewProjectCategorySelectViewModel.swift
  Caladium/Caladium/Views/Componenets/ActionButton.swift
  Caladium/Caladium/Views/Componenets/BottomToolbar.swift
  Caladium/Caladium/Views/Componenets/CameraPopup.swift
  Caladium/Caladium/Views/Componenets/DeleteConfirmPopup.swift
  Caladium/Caladium/Views/Componenets/FormatSelectPopupView.swift
  Caladium/Caladium/Views/Componenets/PhotoDeleteConfirmPopup.swift
  Caladium/Caladium/Views/Componenets/PhotoFrame.swift
  Caladium/Caladium/Views/Componenets/Popup/CameraPopup.swift
  Caladium/Caladium/Views/Componenets/Popup/CategoryChangePopup.swift
  Caladium/Caladium/Views/Componenets/Popup/DeleteConfirmPopup.swift
  Caladium/Caladium/Views/Componenets/Popup/FormatSelectPopupView.swift
  Caladium/Caladium/Views/Componenets/Popup/PhotoDeleteConfirmPopup.swift
  Caladium/Caladium/Views/Componenets/ProjectAddButton.swift
  Caladium/Caladium/Views/Componenets/ProjectThumbnail.swift
  Caladium/Caladium/Views/Screen/AnimationResultView.swift
  Caladium/Caladium/Views/Screen/GIFCreatorView.swift
  Caladium/Caladium/Views/Screen/HomeView.swift
  Caladium/Caladium/Views/Screen/NewProjectCategorySelectView.swift
  Caladium/Caladium/Views/Screen/OnboardingView.swift
  Caladium/Caladium/Views/Screen/PhotoConfirmView.swift
  Caladium/Caladium/Views/Screen/PhotoDetailView.swift
  Caladium/Caladium/Views/Screen/ProjectDetailView.swift
Labels: chore, feat
